version: "3.7"

services:
  postgres:
    image: postgres:11.2
    container_name: postgres-prodeej
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_DB=prodeej
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  neo4j:
    image: neo4j:4.1.1
    container_name: neo4j-prodeej
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_connector_bolt_advertised__address=neo4j:7687

    volumes:
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/data:/var/lib/neo4j/data
      - ./data/neo4j/conf:/var/lib/neo4j/conf
      - ./data/neo4j/logs:/var/lib/neo4j/logs

  old-neo4j:
    image: neo4j:3.5.7
    container_name: neo4j-prodeej
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test
      #- NEO4J_dbms_connector_bolt_advertised__address=neo4j:7687
      - NEO4J_dbms_shell_enabled='true'

    volumes:
      - ./data/old-neo4j/data:/var/lib/neo4j/data

  api:
    image: registry.gitlab.com/flexper/prodeej/prodeej-backend:local-0.13
    container_name: api
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NEO_HOST=neo4j
      - NEO_NAME=neo4j
      - NEO_PASSWORD=test
      - DATABASE_HOST=postgres
      - DATABASE_NAME=prodeej
      - DATABASE_PORT=5432
      - DATABASE_USER=docker
      - PORT=4000
      - NEO_PORT=7474
      - DATABASE_ACCESS_KEY=docker
      - ADMIN_EMAIL=alertes@prodeej.com
      - INSEE_CONSUMER_KEY=_bHql6xA10y86wpbK0tbrJAKWRUa
      - INSEE_CONSUMER_SECRET=M_pjaSVePLbg3guzpz44eSSm6MEa
      - INSEE_ACCESS_TOKEN=f8f67b12-d9f5-3af6-a332-6e38513b5286
      - INSEE_BASE_URL=https://api.insee.fr
      - NEO4J_PORT=7687
      - NEO4J_HOST=neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=test
      - NEO4J_SCHEME=bolt
      - STORAGE_ACCESS_KEY_ID=XXXXXXXXX
      - STORAGE_SECRET_ACCESS_KEY=XXXXXXXXX
      - STORAGE_REGION=XXXXXXXXX
      - STORAGE_ENDPOINT=XXXXXXXXX
      - STORAGE_BUCKET=XXXXXXXXX
      - ISBN_API_KEY=44624_01e357b3fa9accd7a4614f386d530143
