apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-conf
  namespace: default
data:
  NEO4J_AUTH: neo4j/test
  NEO4J_dbms_shell_enabled: "true"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j-statefulset
  namespace: default
spec:
  selector:
    matchLabels:
      app: neo4j-statefulset
  replicas: 1
  serviceName: neo4j-statefulset-svc
  template:
    metadata:
      labels:
        app: neo4j-statefulset
    spec:
      containers:
      - name: neo4j-statefulset
        image: neo4j:4.1.1
        envFrom:
          - configMapRef:
              name: neo4j-conf
              optional: false
        imagePullPolicy: Always
        ports:
          - containerPort: 7474
            name: http
            protocol: TCP
          - containerPort: 7687
            name: bolt
            protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts :
          - name: data-neo4j
            mountPath: /var/lib/neo4j/data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: data-neo4j
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: neo4j-statefulset
    namespace: default
  name: neo4j-statefulset-svc
spec:
  type: ClusterIP
  selector:
    app: neo4j-statefulset
  ports:
    - name: http
      protocol: TCP
      port: 7474
      targetPort: 7474
    - name: bolt
      protocol: TCP
      port: 7687
      targetPort: 7687